version: "3.3"

services:
  db:
   image: postgres:14.1-alpine
   container_name: postgres
   restart: always
   tty: true
   volumes:
     - ../.pgdata:/var/lib/postgresql/data
   environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=secret
     - POSTGRES_DB=database
   ports:
     - 0.0.0.0:5432:5432
  mongodb:
    platform: linux/x86_64
    image: mongo:latest
    container_name: mongodb
    ports:
      - 0.0.0.0:27017:27017
    volumes:
      - ../.mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
  zookeeper:
    platform: linux/x86_64
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
  kafka:
    platform: linux/x86_64
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    ports:
      - "29092:29092"
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
  kafkaui:
    platform: linux/x86_64
    container_name: kafkaui
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:9092"
      KAFKA_CLUSTERS_0_NAME: "KAFKA LOCAL"
      KAFKA_CLUSTERS_0_ZOOKEEPER: "zookeeper:2181"
  web:
    platform: linux/x86_64
    container_name: web
    build: .
    depends_on:
      - kafka
      - db
    environment:
      - APP_DATABASE_HOST=postgres://postgres:secret@db:5432/database?sslmode=disable
      - APP_HOST=0.0.0.0
      - APP_PORT=5000
      - APP_KAFKA_HOST=kafka
      - APP_KAFKA_PORT=29092
    command: go run . server
    ports:
      - "0.0.0.0:5000:5000"
    volumes:
      -  .:/go/src/app
volumes:
  .pgdata:
    driver: local
  .mongo:
    driver: local